#!/bin/sh /etc/rc.common
START=15
USE_PROCD=1

start_service() {
    procd_open_instance
#Wireless
#RADIO 5
    tx_power_radio1=$(uci get wireless.wifi1.TXPowLim5G)
    tx_chainmask_radio1=$(uci get wireless.wifi1.txchainmask)
    rx_chainmask_radio1=$(uci get wireless.wifi1.rxchainmask)
    shortgi_radio1=$(uci get wireless.@wifi-iface[1].shortgi)
    distance_radio1=$(uci get wireless.wifi1.distance)
    hidden_radio1=$(uci get wireless.@wifi-iface[1].hidden)
    dgackdisable=$(uci get wireless.@wifi-iface[1].dgackdisable)
    amsdu1=$(uci get wireless.@wifi-iface[1].amsdu)
    ampdu1=$(uci get wireless.@wifi-iface[1].ampdu)
    kwnnoiseoff1=$(uci get wireless.wifi1.kwnnoiseoff)
    stream1=$(uci get wireless.wifi1.spatialstream)
    ddrs1=$(uci get wireless.wifi1.ddrsstatus)
    ddrsrate1=$(uci get wireless.wifi1.ddrsrate)
    ddrsminrate1=$(uci get wireless.wifi1.ddrsminrate)
    ddrsmaxrate1=$(uci get wireless.wifi1.ddrsmaxrate)
    ddrsinctimer1=$(uci get wireless.wifi1.ddrsinctimer)
    ddrsdectimer1=$(uci get wireless.wifi1.ddrsdectimer)
    ddrsincthrld1=$(uci get wireless.wifi1.ddrsincthrld)
    atpcstatus1=$(uci get wireless.wifi1.atpcstatus)
    atpcpower1=$(uci get wireless.wifi1.atpcpower)
    gain1=$(uci get wireless.wifi1.antennagain)
    frag1=$(uci get wireless.wifi1.assemfrag)
    maxsize1=$(uci get wireless.wifi1.maxsize)
    fragsize1=$(uci get wireless.wifi1.fragsize)
#RADIO 2.4
    tx_power_radio2=$(uci get wireless.wifi0.TXPowLim2G)
    hidden_radio0=$(uci get wireless.@wifi-iface[0].hidden)
#Ethernet
    eth_timer=$(uci get ethernet.ethernet.ethtimer)
    eth_mtu=$(uci get network.lan.mtu)
#VLAN
    tagmgmt=$(uci get vlan.vlan.tagmgmt)
#TFTP
    tftpkeepset=$(uci get tftp.tftp.keepset)
    http=$(uci get tftp.http)
    httpfiletype=$(uci get tftp.http.filetype)
    httpoptype=$(uci get tftp.http.optype)
#VARIANT
    maxsu=$(uci get variant.variant.maxsu)

    if [ "$eth_timer" == "" ]
    then
        uci set ethernet.ethernet.ethtimer='0'
    fi
    if [ "$tx_power_radio1" == "" ]
    then
        uci set wireless.wifi1.TXPowLim5G='23'
    fi
    if [ "$tx_power_radio2" == "" ]
    then
        uci set wireless.wifi0.TXPowLim2G='20'
    fi
    if [ "$tx_chainmask_radio1" == "" ]
    then
        uci set wireless.wifi1.txchainmask='3'
    fi
    if [ "$rx_chainmask_radio1" == "" ]
    then
        uci set wireless.wifi1.rxchainmask='3'
    fi
    if [ "$shortgi_radio1" == "" ]
    then
        uci set wireless.@wifi-iface[1].shortgi='1'
    fi
    if [ "$distance_radio1" == "" ]
    then
        uci set wireless.wifi1.distance='5'
    fi
    if [ "$hidden_radio1" == "" ]
    then
        uci set wireless.@wifi-iface[1].hidden='0'
    fi
    if [ "$dgackdisable" == "" ]
    then
        uci set wireless.@wifi-iface[1].dgackdisable='0'
    fi
    if [ "$amsdu1" == "" ]
    then
        uci set wireless.@wifi-iface[1].amsdu='4'
    fi
    if [ "$ampdu1" == "" ]
    then
        uci set wireless.@wifi-iface[1].ampdu='64'
    fi
    if [ "$kwnnoiseoff1" == "" ]
    then
        uci set wireless.wifi1.kwnnoiseoff='15'
    fi
    if [ "$stream1" == "" ]
    then
        uci set wireless.wifi1.spatialstream='1'
    fi
    if [ "$ddrs1" == "" ]
    then
        uci set wireless.wifi1.ddrsstatus='1'
    fi
    if [ "$ddrsrate1" == "" ]
    then
        uci set wireless.wifi1.ddrsrate='3'
    fi
    if [ "$ddrsminrate1" == "" ]
    then
        uci set wireless.wifi1.ddrsminrate='0'
    fi
    if [ "$ddrsmaxrate1" == "" ]
    then
        uci set wireless.wifi1.ddrsmaxrate='9'
    fi
    if [ "$ddrsinctimer1" == "" ]
    then
        uci set wireless.wifi1.ddrsinctimer='2'
    fi
    if [ "$ddrsdectimer1" == "" ]
    then
        uci set wireless.wifi1.ddrsdectimer='1'
    fi
    if [ "$ddrsincthrld1" == "" ]
    then
        uci set wireless.wifi1.ddrsincthrld='3'
    fi
# Auto Stream is not supported in current release...for upgrade support restting to single
    if [ $stream1 -eq "3" ]; then
        uci set wireless.wifi1.spatialstream='1'
        uci set wireless.wifi1.ddrsminrate='0'
        uci set wireless.wifi1.ddrsmaxrate='9'
        uci set wireless.wifi1.ddrsrate='3'
    fi
    if [ "$atpcstatus1" == "" ]
    then
        uci set wireless.wifi1.atpcstatus='2'
    fi
    if [ "$atpcpower1" == "" ]
    then
        uci set wireless.wifi1.atpcpower='26'
    fi
    if [ "$gain1" == "" ]
    then
        uci set wireless.wifi1.antennagain='23'
    fi
    if [ "$frag1" == "" ]
    then
        uci set wireless.wifi1.assemfrag='0'
    fi
    if [ "$maxsize1" == "" ]
    then
        uci set wireless.wifi1.maxsize='1200'
    fi
    if [ "$fragsize1" == "" ]
    then
        uci set wireless.wifi1.fragsize='1000'
    fi
    if [ "$eth_mtu" == "" ]
    then
        uci set network.lan.mtu='1500'
    fi
    if [ "$tagmgmt" == "" ]
    then
        uci set vlan.vlan.tagmgmt='0'
    fi
#5 Radio Default values
    uci set wireless.wifi1.enable_ol_stats='1'
#2.4 Radio Default values
    uci set wireless.wifi0.txchainmask='3'
    uci set wireless.wifi0.rxchainmask='3'
    uci set wireless.wifi0.rate='0'
    if [ "$hidden_radio0" == "" ]
    then
        uci set wireless.@wifi-iface[0].hidden='1'
    fi
#DHCP
    ignore=$(uci get dhcp.lan.ignore)
    if [ "$ignore" == "" ]
    then
        uci set dhcp.lan=dhcp
        uci set dhcp.lan.interface='lan'
        uci set dhcp.lan.dhcpv6='server'
        uci set dhcp.lan.ra='server'
        uci set dhcp.lan.start='192.168.1.100'
        uci set dhcp.lan.limit='192.168.1.150'
        uci set dhcp.lan.leasetime='43200'
        uci set dhcp.lan.ignore='1'
    fi
#TFTP
    if [ "$tftpkeepset" == "" ]
    then
        uci set tftp.tftp.keepset='1'
    fi
    if [ "$http" == "" ]
    then
        uci set tftp.http='http'
        uci set tftp.http.filetype='1'
        uci set tftp.http.optype='0'
    fi
#VARIANT
    uci set variant.variant.buildno='191118'
    if [ "$maxsu" == "" ]
    then
        uci set variant.variant.maxsu ='1'
    fi

    dmesg -n 1

    procd_close_instance
}
