#!/bin/sh /etc/rc.common
START=93
USE_PROCD=1

service_triggers() {
        procd_add_reload_trigger "telnetssh"
}

start_service() {

    procd_open_instance
    telnet=$(uci get telnetssh.telnet.status)
    ssh=$(uci get telnetssh.ssh.status)
    tnetsessions=$(uci get telnetssh.telnet.sessions)
    sshsessions=$(uci get telnetssh.ssh.sessions)

    if [ $telnet -eq "1" ]; then
        /etc/init.d/telnet start
    else
        /etc/init.d/telnet stop
    fi

    if [ $ssh -eq "1" ]; then
        /etc/init.d/sshd stop
        /etc/init.d/sshd start
    else
        /etc/init.d/sshd stop
    fi
    
    #obtain rule number if already rule exists
    sshrule=$(iptables --list --line-numbers | grep ssh | awk '{ for(i=1; i <= 1;i++) {print $i } }')
    telnetrule=$(iptables --list --line-numbers | grep telnet | awk '{ for(i=1; i <= 1; i++) {print $i } }')
    
    if [ "$sshrule" == "" ]
    then
        iptables -A INPUT -p tcp --syn --dport 22 -m connlimit --connlimit-above $sshsessions -j DROP
    else
        iptables -R INPUT $sshrule -p tcp --syn --dport 22 -m connlimit --connlimit-above $sshsessions -j DROP
    fi
    
    if [ "$telnetrule" == "" ]
    then
        iptables -A INPUT -p tcp --syn --dport 23 -m connlimit --connlimit-above $tnetsessions -j DROP
    else
        iptables -R INPUT $telnetrule -p tcp --syn --dport 23 -m connlimit --connlimit-above $tnetsessions -j DROP
    fi

    procd_close_instance
}


