#!/bin/sh /etc/rc.common
START=93
USE_PROCD=1

service_triggers() {
        procd_add_reload_trigger "vlan"
}

start_service() {

    procd_open_instance
    status=$(uci get vlan.vlan.status)
    mode=$(uci get vlan.vlan.mode)
    mgmtvlan=$(uci get vlan.vlan.mgmtvlan)
    accvlan=$(uci get vlan.vlan.accessvlan)
    trunkopt=$(uci get vlan.vlan.trunkoption)
    trunkvlan=$(uci get vlan.vlan.trunkvlan)
    svlan=$(uci get vlan.vlan.svlan)
    svlanethertype=$(uci get vlan.vlan.svlanethertype)


    if [ $status -eq "2" ]; then
        mode=-1
        mgmtvlan=0
        accvlan=0
    fi
#Setting Mode to Trunk if QinQ configured
#Setting svlan and svlanethertype to -1 if not QinQ
    if [ $mode -eq "3" ]; then
        mode=2
    else
        svlan=0
        svlanethertype=0
    fi
    iwpriv ath1 kwn_vlan_mode $mode
    iwpriv ath1 kwn_mgmt_vid $mgmtvlan
    iwpriv ath1 kwn_acc_vid $accvlan
    iwpriv ath1 kwn_allowuntag $trunkopt
    iwpriv ath1 kwn_vid_del "0"
    [ -n "$trunkvlan" ] && {
            for id in $trunkvlan; do
            iwpriv ath1 kwn_vid_add "$id"
            done
    }
    iwpriv ath1 kwn_svlan_id $svlan
    iwpriv ath1 kwn_setherType $svlanethertype

    procd_close_instance
}


