#!/bin/sh /etc/rc.common
START=93
USE_PROCD=1

service_triggers() {
        procd_add_reload_trigger "vlan"
}

start_service() {

    procd_open_instance
    status=$(uci get vlan.vlan.status)
    mode=$(uci get vlan.vlan.mode)
    mgmtvlan=$(uci get vlan.vlan.mgmtvlan)
    accvlan=$(uci get vlan.vlan.accessvlan)
    trunkopt=$(uci get vlan.vlan.trunkoption)
    trunkvlan=$(uci get vlan.vlan.trunkvlan)
    svlan=$(uci get vlan.vlan.svlan)
    svlanethertype=$(uci get vlan.vlan.svlanethertype)
    bda=$(uci get vlan.vlan.bda)
    bsa=$(uci get vlan.vlan.bsa)
    bvid=$(uci get vlan.vlan.bvid)
    bisid=$(uci get vlan.vlan.bisid)
    tagmgmt=$(uci get vlan.vlan.tagmgmt)


# VLAN Disable: Mgmt vlan must be set to 0 since it is used 
# in driver for forwarding the mgmt VLAN packets to local host.
    if [ $status -eq "2" ]; then
        mode=-1
        mgmtvlan=0
        accvlan=0
        tagmgmt=0
    else
# VLAN Enable: Mgmt vlan > 1 then enable tagged management
        if [ $mgmtvlan -ge "2" ]; then
            tagmgmt=1
        else
            tagmgmt=0
        fi
    fi
    if [ $mode -eq "4" ]; then
        svlanethertype="0xa888"
    fi
    iwpriv ath1 kwn_vlan_mode $mode
    iwpriv ath1 kwn_mgmt_vid $mgmtvlan
    iwpriv ath1 kwn_acc_vid $accvlan
    iwpriv ath1 kwn_allowuntag $trunkopt
    iwpriv ath1 kwn_vid_del "0"
    [ -n "$trunkvlan" ] && {
            for id in $trunkvlan; do
            iwpriv ath1 kwn_vid_add "$id"
            done
    }
    iwpriv ath1 kwn_svlan_id $svlan
    iwpriv ath1 kwn_setherType $svlanethertype

#addmac ioctl is used for link test, vlan bda and bsa
#set tput dur to 0 and reset kwn_flag is set to 0
    iwpriv ath1 kwn_flag 2
    iwpriv ath1 addmac $bda
    iwpriv ath1 kwn_flag 3
    iwpriv ath1 addmac $bsa
    iwpriv ath1 kwn_pbb_bvid $bvid
    iwpriv ath1 kwn_pbb_bisid $bisid
    iwpriv ath1 kwn_tagmgmt $tagmgmt

    procd_close_instance
}


