#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

USE_PROCD=1
PROG=/usr/sbin/telnetd

start_service() {
		procd_open_instance
        telnetstat=$(uci get telnetssh.telnet.status)
        if [ $telnetstat -eq "1" ]; then
		    procd_set_param command "$PROG" -F -l /usr/sbin/cli-login.sh
        fi
		#procd_set_param limits core="unlimited"
		procd_close_instance
}
