#!/bin/sh /etc/rc.common
# LED init script

LED_BIN="/usr/bin/leds"

START=99

USE_PROCD=1

service_triggers() {
    procd_add_reload_trigger "system"
}


start_service() {        
    local status="$(uci_get system.led.status)"

    if [ "${status}" == "1" ] ; then
        echo "Starting LED"
        procd_open_instance
        procd_set_param respawn
        procd_set_param command "$LED_BIN"

        procd_close_instance
    fi
}                 

stop() {
	killall leds
} 
