#!/bin/sh /etc/rc.common

CFG_BIN="/usr/sbin/kwn_ipaddr"

START=77
USE_PROCD=1

start_service() {
   echo "Starting ipaddrbrlan"
   procd_open_instance
   procd_set_param respawn
   procd_set_param command "$CFG_BIN"

 procd_close_instance
}

